### ISSUE TITLE
Falta o arquivo package.json

### ISSUE THREAD

**Issue by ismarsantos** [gilcierweb/simple-realtime-message#1]
╭─ismar@acer ~/simple-realtime-message-master 
╰─$ npm install
npm WARN saveError ENOENT: no such file or directory, open '/home/ismar/simple-realtime-message-master/package.json'

**Comment by gilcierweb** [comment]
Olá, não falta, está em /public

var socket  = require( './public/node_modules/socket.io' );
var express = require('./public/node_modules/express');

**Comment by ismarsantos** [comment]
Acabei de ver agora, depois que havia criado hehe obrigado, (voltei aqui para avisar), então estou tentando usar o socket.io com ActionCable você saber dizer se é possível?
